# Generated by Django 4.1 on 2024-07-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_profile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="joindate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
