# Generated by Django 4.1 on 2024-07-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="total_items_purchased",
            field=models.IntegerField(default=0),
        ),
    ]
