# Generated by Django 4.1 on 2024-07-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_product_total_items_purchased"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="total_items_purchased",
        ),
    ]
