# Generated by Django 4.1 on 2024-07-10 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_remove_product_total_items_purchased"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
