# Generated by Django 4.1 on 2024-07-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_orderitem_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="created_at",
        ),
    ]
