# Generated by Django 4.1 on 2024-07-10 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_remove_orderitem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
